### ISSUE TITLE
Rust packages: I can't update rust package with `cargoLock`

### ISSUE THREAD

**Issue by selfuryon** [Mic92/nix-update#154]
Hello!
I can't update rust package with `cargoLock` attribute, it failed. An example package is [here](https://github.com/nix-community/ethereum.nix/blob/main/packages/clients/consensus/lighthouse/default.nix#L38). The output of my attempt:
```console
$ nix-update --flake lighthouse
nix eval --json --impure --expr
let

  inherit (builtins) getFlake stringLength substring;
  currentSystem = builtins.currentSystem;
  flake = getFlake "/home/syakovlev/src/private/ethereum.nix";
  pkg = flake.packages.${currentSystem}.lighthouse or flake.lighthouse;
  inherit (flake) outPath;
  outPathLen = stringLength outPath;
  sanitizePosition = { file, ... }@pos:
    assert substring 0 outPathLen file == outPath;
    pos // { file = "/home/syakovlev/src/private/ethereum.nix" + substring outPathLen (stringLength file - outPathLen) file; };

  raw_version_position = sanitizePosition (builtins.unsafeGetAttrPos "version" pkg);

  position = if pkg ? isRubyGem then
    raw_version_position
  else if pkg ? isPhpExtension then
    raw_version_position
   else
    sanitizePosition (builtins.unsafeGetAttrPos "src" pkg);
in {
  name = pkg.name;
  old_version = pkg.version or (builtins.parseDrvName pkg.name).version;
  inherit raw_version_position;
  filename = position.file;
  line = position.line;
  urls = pkg.src.urls or null;
  url = pkg.src.url or null;
  rev = pkg.src.rev or null;
  hash = pkg.src.outputHash or null;
  vendor_hash = pkg.vendorHash or null;
  vendor_sha256 = pkg.vendorSha256 or null;
  cargo_deps = pkg.cargoDeps.outputHash or null;
  cargo_lock =
    if pkg ? cargoDeps.lockFile then
      (sanitizePosition { file = pkg.cargoDeps.lockFile; }).file
    else
      null;
  npm_deps = pkg.npmDeps.outputHash or null;
  tests = builtins.attrNames (pkg.passthru.tests or {});
  has_update_script = false;
  src_homepage = pkg.src.meta.homepage or null;
  changelog = pkg.meta.changelog or null;
} --extra-experimental-features flakes nix-command
error: assertion '((substring 0 outPathLen file) == outPath)' failed

       at «string»:11:5:

           10|   sanitizePosition = { file, ... }@pos:
           11|     assert substring 0 outPathLen file == outPath;
             |     ^
           12|     pos // { file = "/home/syakovlev/src/private/ethereum.nix" + substring outPathLen (stringLength file - outPathLen) file; };
Traceback (most recent call last):
  File "/nix/store/9xxnv5prf7mryxq06qkifr391dnfb824-nix-update-0.16.0/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/9xxnv5prf7mryxq06qkifr391dnfb824-nix-update-0.16.0/lib/python3.11/site-packages/nix_update/__init__.py", line 287, in main
    package = update(options)
              ^^^^^^^^^^^^^^^
  File "/nix/store/9xxnv5prf7mryxq06qkifr391dnfb824-nix-update-0.16.0/lib/python3.11/site-packages/nix_update/update.py", line 284, in update
    package = eval_attr(opts)
              ^^^^^^^^^^^^^^^
  File "/nix/store/9xxnv5prf7mryxq06qkifr391dnfb824-nix-update-0.16.0/lib/python3.11/site-packages/nix_update/eval.py", line 136, in eval_attr
    res = run(cmd)
          ^^^^^^^^
  File "/nix/store/9xxnv5prf7mryxq06qkifr391dnfb824-nix-update-0.16.0/lib/python3.11/site-packages/nix_update/utils.py", line 36, in run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/nix/store/hx2c957wpwa6i3fz0wiwhg72sfgq62k1-python3-3.11.2/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--json', '--impure', '--expr', '\nlet\n  \n  inherit (builtins) getFlake stringLength substring;\n  currentSystem = builtins.currentSystem;\n  flake = getFlake "/home/syakovlev/src/private/ethereum.nix";\n  pkg = flake.packages.${currentSystem}.lighthouse or flake.lighthouse;\n  inherit (flake) outPath;\n  outPathLen = stringLength outPath;\n  sanitizePosition = { file, ... }@pos:\n    assert substring 0 outPathLen file == outPath;\n    pos // { file = "/home/syakovlev/src/private/ethereum.nix" + substring outPathLen (stringLength file - outPathLen) file; };\n\n  raw_version_position = sanitizePosition (builtins.unsafeGetAttrPos "version" pkg);\n\n  position = if pkg ? isRubyGem then\n    raw_version_position\n  else if pkg ? isPhpExtension then\n    raw_version_position\n   else\n    sanitizePosition (builtins.unsafeGetAttrPos "src" pkg);\nin {\n  name = pkg.name;\n  old_version = pkg.version or (builtins.parseDrvName pkg.name).version;\n  inherit raw_version_position;\n  filename = position.file;\n  line = position.line;\n  urls = pkg.src.urls or null;\n  url = pkg.src.url or null;\n  rev = pkg.src.rev or null;\n  hash = pkg.src.outputHash or null;\n  vendor_hash = pkg.vendorHash or null;\n  vendor_sha256 = pkg.vendorSha256 or null;\n  cargo_deps = pkg.cargoDeps.outputHash or null;\n  cargo_lock =\n    if pkg ? cargoDeps.lockFile then\n      (sanitizePosition { file = pkg.cargoDeps.lockFile; }).file\n    else\n      null;\n  npm_deps = pkg.npmDeps.outputHash or null;\n  tests = builtins.attrNames (pkg.passthru.tests or {});\n  has_update_script = false;\n  src_homepage = pkg.src.meta.homepage or null;\n  changelog = pkg.meta.changelog or null;\n}', '--extra-experimental-features', 'flakes nix-command']' returned non-zero exit status 1.
```
Without `cargoLock` everything works fine.
I will try to investigate how to do that, and if it isn't too hard for me I will make PR.

Ref: https://github.com/nix-community/ethereum.nix/issues/218

**Comment by figsoda** [comment]
Can you check if it works on master? https://github.com/Mic92/nix-update/commit/927f47a36ead7db8742c76468712d8aed08f7fab should be able to fix that

**Comment by Mic92** [comment]
Also bumped a release: https://github.com/Mic92/nix-update/releases/tag/0.17.0

**Comment by selfuryon** [comment]
Cool, it works now! Thanks!
