### ISSUE TITLE
hash mismatch when trying to update kopia

### ISSUE THREAD

**Issue by bbigras** [Mic92/nix-update#16]
```
❯ nix-update kopia

[...]

The package kopia-0.6.3 will be fetched as follows:
> fetchFromGitHub {
>   owner = "kopia";
>   repo = "kopia";
>   rev = "v0.6.3";
>   sha256 = "1wz4sqjcih1m4bjxxdrsggai931q72zz8ikf2rwkp4alz12wr355";
> }

trying https://github.com/kopia/kopia/archive/v0.6.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    680      0 --:--:-- --:--:-- --:--:--   683
100 14.5M    0 14.5M    0     0  2791k      0 --:--:--  0:00:05 --:--:-- 3038k
unpacking source archive /build/v0.6.3.tar.gz
hash mismatch in fixed-output derivation '/nix/store/9hjz4nv225khz9lqdcracyjrjykd1hvh-source':
  wanted: sha256:0000000000000000000000000000000000000000000000000000
  got:    sha256:0pvna3zrhwv412rarlfxgyh8d6xdxp2glx14xyn7n2xzvb0sz4i7
error: build of '/nix/store/yplp86z34fi0spzavamshw13qibsdwjz-source.drv' failed
Traceback (most recent call last):
  File "/nix/store/x3v8v59ra6zf0vanc6hxxyzgkyl7w2vp-nix-update-0.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/x3v8v59ra6zf0vanc6hxxyzgkyl7w2vp-nix-update-0.1/lib/python3.8/site-packages/nix_update/__init__.py", line 142, in main
    package = update(options)
  File "/nix/store/x3v8v59ra6zf0vanc6hxxyzgkyl7w2vp-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 82, in update
    update_src_hash(opts, package.filename, package.hash)
  File "/nix/store/x3v8v59ra6zf0vanc6hxxyzgkyl7w2vp-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 42, in update_src_hash
    target_hash = nix_prefetch([f"(import {opts.import_path} {{}}).{opts.attribute}"])
  File "/nix/store/x3v8v59ra6zf0vanc6hxxyzgkyl7w2vp-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 37, in nix_prefetch
    res = run(["nix-prefetch"] + cmd)
  File "/nix/store/x3v8v59ra6zf0vanc6hxxyzgkyl7w2vp-nix-update-0.1/lib/python3.8/site-packages/nix_update/utils.py", line 32, in run
    return subprocess.run(command, cwd=cwd, check=check, text=True, stdout=stdout)
  File "/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '(import ./. {}).kopia']' returned non-zero exit status 1.
```

for the version:
/nix/store/f2psh8ldz2a1svicp2a1l20x38ik1qj2-nixpkgs-review-2.3.1/bin/nix-review

**Comment by Mic92** [comment]
nix-prefetch is broken. We update the version we have in master to the latest commit.

**Comment by bbigras** [comment]
Are you saying that I just need to use the latest version of nix-review? I tried nur.repos.mic92.nix-update and master (Mic92/nix-update) with the same result.

I probably didn't understand what you said.

**Comment by Mic92** [comment]
No. [nix-prefetch](https://github.com/msteen/nix-prefetch), which is used by nix-update under the hood has a bug that was fixed in https://github.com/msteen/nix-prefetch/pull/12. However nixpkgs still has the unfixed version. This needs to be bumped.

**Comment by bbigras** [comment]
Gotcha. Thanks.

**Comment by Mic92** [comment]
Patch for nix-update should have landed in master.
