### ISSUE TITLE
Version vs GitHub tag

### ISSUE THREAD

**Issue by doronbehar** [Mic92/nix-update#19]
Here's tectonic's expression:

```nix
rustPlatform.buildRustPackage rec {
  pname = "tectonic";
  version = "0.1.15";

  src = fetchFromGitHub {
    owner = "tectonic-typesetting";
    repo = "tectonic";
    rev = "tectonic@${version}";
    sha256 = "0pzhdfsi4jsj9p5cv8ia4kc4inl7q7jsw694dfyxkcpka6ywyzsh";
  };
```

They use an awful revisions schema, I know. I'm a bit surprised though that `nix-update` isn't resiliant to this:

```
>>> nix-update --version 0.1.16 tectonic
$ nix eval --json (with import ./. {};
    let
      pkg = tectonic;
      position = if pkg ? isRubyGem then
        builtins.unsafeGetAttrPos "version" pkg
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoSha256 or null;
    })
Traceback (most recent call last):
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/__init__.py", line 142, in main
    package = update(options)
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 65, in update
    package = eval_attr(opts)
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/eval.py", line 57, in eval_attr
    raise UpdateError(
nix_update.errors.UpdateError: Nix's builtins.parseDrvName could not parse the version from tectonic-tectonic%400.1.16
```

I'd expect it to just update what is written in `version = `. When `nix-update` tries to fetch the latest tag by itself, it fails similarly:

```
>>> nix-update tectonic
$ nix eval --json (with import ./. {};
    let
      pkg = tectonic;
      position = if pkg ? isRubyGem then
        builtins.unsafeGetAttrPos "version" pkg
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoSha256 or null;
    })
fetch https://github.com/tectonic-typesetting/tectonic/releases.atom
Update 0.1.15 -> tectonic%400.1.16 in /home/doron/repos/nixpkgs/pkgs/tools/typesetting/tectonic/default.nix
$ nix-prefetch (import ./. {}).tectonic
The package tectonic-tectonic%400.1.16 will be fetched as follows:
> fetchFromGitHub {
>   owner = "tectonic-typesetting";
>   repo = "tectonic";
>   rev = "tectonic@tectonic%400.1.16";
>   sha256 = "0pzhdfsi4jsj9p5cv8ia4kc4inl7q7jsw694dfyxkcpka6ywyzsh";
> }

trying https://github.com/tectonic-typesetting/tectonic/archive/tectonic@tectonic%400.1.16.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   159  100   159    0     0    395      0 --:--:-- --:--:-- --:--:--   396
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download source from any mirror
builder for '/nix/store/ja73m41fanwdcxf22xlypp8zr0iwwxvf-source.drv' failed with exit code 1
error: build of '/nix/store/ja73m41fanwdcxf22xlypp8zr0iwwxvf-source.drv' failed
Traceback (most recent call last):
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/__init__.py", line 142, in main
    package = update(options)
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 82, in update
    update_src_hash(opts, package.filename, package.hash)
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 42, in update_src_hash
    target_hash = nix_prefetch([f"(import {opts.import_path} {{}}).{opts.attribute}"])
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 37, in nix_prefetch
    res = run(["nix-prefetch"] + cmd)
  File "/nix/store/c9za2shgsx4yfc5dh1r0xgmxaxgp11c0-nix-update-0.1/lib/python3.8/site-packages/nix_update/utils.py", line 32, in run
    return subprocess.run(command, cwd=cwd, check=check, text=True, stdout=stdout)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '(import ./. {}).tectonic']' returned non-zero exit status 1.
```

**Comment by Mic92** [comment]
This is the same issue as reported here: https://github.com/Mic92/nix-update/issues/9
