### ISSUE TITLE
Fails to determine runtime directory on macOS

### ISSUE THREAD

**Issue by siraben** [Mic92/nix-update#22]
```
$ nix-update driftnet                                     
$ nix eval --json (with import ./. {};
    let
      pkg = driftnet;
      position = if pkg ? isRubyGem then
        builtins.unsafeGetAttrPos "version" pkg
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoSha256 or null;
    })
fetch https://github.com/deiv/driftnet/releases.atom
Update 1.1.5 -> 1.3.0 in /Users/siraben/Git/forks/nixpkgs/pkgs/tools/networking/driftnet/default.nix
$ nix-prefetch (import ./. {}).driftnet
error: Could not determine the runtime directory (i.e. XDG_RUNTIME_DIR).
Traceback (most recent call last):
  File "/nix/store/iyvrjsrqn7najwmwh5y13dmpg1z7068m-nix-update-0.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/iyvrjsrqn7najwmwh5y13dmpg1z7068m-nix-update-0.1/lib/python3.8/site-packages/nix_update/__init__.py", line 142, in main
    package = update(options)
  File "/nix/store/iyvrjsrqn7najwmwh5y13dmpg1z7068m-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 82, in update
    update_src_hash(opts, package.filename, package.hash)
  File "/nix/store/iyvrjsrqn7najwmwh5y13dmpg1z7068m-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 42, in update_src_hash
    target_hash = nix_prefetch([f"(import {opts.import_path} {{}}).{opts.attribute}"])
  File "/nix/store/iyvrjsrqn7najwmwh5y13dmpg1z7068m-nix-update-0.1/lib/python3.8/site-packages/nix_update/update.py", line 37, in nix_prefetch
    res = run(["nix-prefetch"] + cmd)
  File "/nix/store/iyvrjsrqn7najwmwh5y13dmpg1z7068m-nix-update-0.1/lib/python3.8/site-packages/nix_update/utils.py", line 32, in run
    return subprocess.run(command, cwd=cwd, check=check, text=True, stdout=stdout)
  File "/nix/store/65gmh01007csxmd6bbkvas8zkhlw0k7n-python3-3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '(import ./. {}).driftnet']' returned non-zero exit status 1.
```

**Comment by zowoq** [comment]
It's an problem with https://github.com/msteen/nix-prefetch.

I haven't tested it but looks like [it may have been fixed?](https://github.com/msteen/nix-prefetch/compare/0.3.1...master#diff-e4d34fc353097073f2f6ebbdc1d89cbdac9f0edf5354442c2f884839a2e8afb3L230)

**Comment by Mic92** [comment]
You can override the nix-prefetch version here to check if it fixes the issue: https://github.com/Mic92/nix-update/blob/master/default.nix#L19

**Comment by RonanMacF** [comment]
Also having this issue on MacOS

**Comment by Mic92** [comment]
Maybe open an issue on nix-prefetch instead if it is still a problem there.

**Comment by Mic92** [comment]
Is this still a problem with nix-prefetch 0.4?

**Comment by zowoq** [comment]
The `XDG_RUNTIME_DIR` error is fixed but now it fails with `error: Unsupported input type ''.`

https://github.com/msteen/nix-prefetch/issues/14

I'll try to find some time to fix this soon.

**Comment by Mic92** [comment]
Closing the issue than, since needs to be fixed in nix-prefetch.
