### ISSUE TITLE
nix-update does not check all tags for versions on github

### ISSUE THREAD

**Issue by raspher** [Mic92/nix-update#231]
Hi, an example package i've tried to update: [quickwit](https://github.com/quickwit-oss/quickwit/tags) which have a lot of tags. However none of tags were found on first page (?) and it gives up.

modified a little update script to use regex 
```
src = fetchFromGitHub {
    owner = "quickwit-oss";
    repo = pname;
    rev = "v${version}";
    hash = "sha256-stlm3oDMQVoMza3s4JApynXbzhrarfXw3uAxGMZQJqs=";
  };
[...]
  passthru.updateScript = nix-update-script {
    extraArgs = [ "--version-regex" "v([0-9.]+)" ];
   };
```

And i've got this after `nix-update -u quickwit` inside root of nixpkgs repository.
```
--- SHOWING ERROR LOG FOR quickwit-0.6.4 ----------------------

Traceback (most recent call last):
  File "/nix/store/8iq9mwxyzyamsnyrsbgscvflq60n55hm-nix-update-1.2.0/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/8iq9mwxyzyamsnyrsbgscvflq60n55hm-nix-update-1.2.0/lib/python3.11/site-packages/nix_update/__init__.py", line 291, in main
    package = update(options)
              ^^^^^^^^^^^^^^^
  File "/nix/store/8iq9mwxyzyamsnyrsbgscvflq60n55hm-nix-update-1.2.0/lib/python3.11/site-packages/nix_update/update.py", line 352, in update
    update_hash = update_version(
                  ^^^^^^^^^^^^^^^
  File "/nix/store/8iq9mwxyzyamsnyrsbgscvflq60n55hm-nix-update-1.2.0/lib/python3.11/site-packages/nix_update/update.py", line 290, in update_version
    new_version = fetch_latest_version(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8iq9mwxyzyamsnyrsbgscvflq60n55hm-nix-update-1.2.0/lib/python3.11/site-packages/nix_update/version/__init__.py", line 125, in fetch_latest_version
    raise VersionError(
nix_update.errors.VersionError: Not version matched the regex. The following versions were found:
qw-fulmicoton14
qw-meerkat
qw-guilload
qw-fulmicoton13
qw-wal
qw-airmail
qw-fulmicoton12
qw-fulmicoton11
qw-grpc-gossip
qw-fulmicoton10
```
not all versions/tags were listed here, probably didn't check more tags

**Comment by Mic92** [comment]
Ah. I think what happened here is that they spammed a lot of tags to there repository so that actual releases are no longer included.

**Comment by jvanbruegge** [comment]
This is probably fixed by #246 because that only lists releases, not tags

**Comment by Shawn8901** [comment]
Does it make sense possibly also utilize the latest release flag, that can be set via github? 
When creating a release one can select that the new release is also the latest (which upstream hopefully maintains).
We could possibly use another flag, or should we possibly always do that?

That could avoid https://github.com/Mic92/nix-update/issues/271 at least for github releases.

I stumbled around that when checking if i can replace the custom update script of the victoriametrics package in nixpkgs with plain nix-update.
As upstream creates a lot of LTS releases in between its heavily affected by #271, as nix-update just grabs the most recent item from the release.atom file (if i understand the code correctly). 



I can do the coding, just trying to ask before if it make sense.
