### ISSUE TITLE
"IndexError: no such group" when the version regex should have a match

### ISSUE THREAD

**Issue by teto** [Mic92/nix-update#248]
```
 nix-update -vr '7.53.0' datadog-agent 
$ nix eval --json --impure --expr 
let
  
  pkgs = import "/home/teto/nixpkgs";
  args =  builtins.functionArgs pkgs;
  inputs = (if args ? system then { system = builtins.currentSystem; } else {}) //
           (if args ? overlays then { overlays = [ ]; } else {});
  pkg = (pkgs inputs)."datadog-agent";
  sanitizePosition = x: x;

  raw_version_position = sanitizePosition (builtins.unsafeGetAttrPos "version" pkg);

  position = if pkg ? isRubyGem then
    raw_version_position
  else if pkg ? isPhpExtension then
    raw_version_position
   else
    sanitizePosition (builtins.unsafeGetAttrPos "src" pkg);
in {
  name = pkg.name;
  old_version = pkg.version or (builtins.parseDrvName pkg.name).version;
  inherit raw_version_position;
  filename = position.file;
  line = position.line;
  urls = pkg.src.urls or null;
  url = pkg.src.url or null;
  rev = pkg.src.rev or null;
  hash = pkg.src.outputHash or null;
  go_modules = pkg.goModules.outputHash or null;
  go_modules_old = pkg.go-modules.outputHash or null;
  cargo_deps = pkg.cargoDeps.outputHash or null;
  raw_cargo_lock =
    if pkg ? cargoDeps.lockFile then
      let
        inherit (pkg.cargoDeps) lockFile;
        res = builtins.tryEval (sanitizePosition {
          file = toString lockFile;
        });
      in
      if res.success then res.value.file else false
    else
      null;
  composer_deps = pkg.composerRepository.outputHash or null;
  npm_deps = pkg.npmDeps.outputHash or null;
  yarn_deps = pkg.offlineCache.outputHash or null;
  maven_deps = pkg.fetchedMavenDeps.outputHash or null;
  tests = builtins.attrNames (pkg.passthru.tests or {});
  has_update_script = pkg.passthru.updateScript or null != null;
  src_homepage = pkg.src.meta.homepage or null;
  changelog = pkg.meta.changelog or null;
  maintainers = pkg.meta.maintainers or null;
} --extra-experimental-features flakes nix-command
fetch https://github.com/DataDog/datadog-agent/releases.atom
Traceback (most recent call last):
  File "/nix/store/ghzw63n3gphjk92jdil3qwnwf6x975kb-nix-update-1.3.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/ghzw63n3gphjk92jdil3qwnwf6x975kb-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/__init__.py", line 291, in main
    package = update(options)
              ^^^^^^^^^^^^^^^
  File "/nix/store/ghzw63n3gphjk92jdil3qwnwf6x975kb-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/update.py", line 361, in update
    update_hash = update_version(
                  ^^^^^^^^^^^^^^^
  File "/nix/store/ghzw63n3gphjk92jdil3qwnwf6x975kb-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/update.py", line 299, in update_version
    new_version = fetch_latest_version(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ghzw63n3gphjk92jdil3qwnwf6x975kb-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/version/__init__.py", line 95, in fetch_latest_version
    extracted = extract_version(version, version_regex)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ghzw63n3gphjk92jdil3qwnwf6x975kb-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/version/__init__.py", line 58, in extract_version
    group = match.group(1)
            ^^^^^^^^^^^^^^
IndexError: no such group
```
what's funny is that when in a previous run, I had prefixed my regex with `v`, nix-update returned
```
...
  File "/nix/store/ghzw63n3gphjk92jdil3qwnwf6x975kb-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/version/__init__.py", line 125, in fetch_latest_version
    raise VersionError(
nix_update.errors.VersionError: Not version matched the regex. The following versions were found:
7.54.0-installer-0.0.5
6.54.0-installer-0.0.5
7.54.0-installer-0.0.4
7.54.0-installer-0.0.3
7.54.0-installer-0.0.2
6.54.0-installer-0.0.4
6.54.0-installer-0.0.3
6.54.0-installer-0.0.2
7.54.0-rc.1
7.53.0
```
so it did see 7.53.0

while trying to redact this issue, I wanted to share nix-update version but I could not find it from the CLI xD it was installed from nixos-unstable so it should be   `1.3.1`

**Comment by Mic92** [comment]
You need to have one regex capture group in your regex:

```
nix-update -vr '(7.53.0)' datadog-agent
```

**Comment by teto** [comment]
indeed ty
