### ISSUE TITLE
error: value is null while a set was expected

### ISSUE THREAD

**Issue by LordMZTE** [Mic92/nix-update#252]
nix-update fails to run for me while attempting to update an output of [this flake](https://git.mzte.de/lordmzte/dotfiles). The command I ran was `nix-update nushell-plugins -F`.
The relevant file defining the derivation is [here](https://git.mzte.de/LordMZTE/dotfiles/src/branch/master/nix/nushell-plugins.nix).

<details>
    <summary>Full Output</summary>

```
$ nix eval --json --impure --expr 
let
  
  inherit (builtins) getFlake stringLength substring;
  currentSystem = builtins.currentSystem;
  flake = getFlake "/home/lordmzte/dev/dotfiles";
  pkg = flake.packages.${currentSystem}."nushell-plugins" or flake."nushell-plugins";
  inherit (flake) outPath;
  outPathLen = stringLength outPath;
  sanitizePosition = { file, ... }@pos:
        assert substring 0 outPathLen file != outPath
          -> throw "${file} is not in ${outPath}";
        pos // { file = "/home/lordmzte/dev/dotfiles" + substring outPathLen (stringLength file - outPathLen) file; };

  raw_version_position = sanitizePosition (builtins.unsafeGetAttrPos "version" pkg);

  position = if pkg ? isRubyGem then
    raw_version_position
  else if pkg ? isPhpExtension then
    raw_version_position
   else
    sanitizePosition (builtins.unsafeGetAttrPos "src" pkg);
in {
  name = pkg.name;
  old_version = pkg.version or (builtins.parseDrvName pkg.name).version;
  inherit raw_version_position;
  filename = position.file;
  line = position.line;
  urls = pkg.src.urls or null;
  url = pkg.src.url or null;
  rev = pkg.src.rev or null;
  hash = pkg.src.outputHash or null;
  go_modules = pkg.goModules.outputHash or null;
  go_modules_old = pkg.go-modules.outputHash or null;
  cargo_deps = pkg.cargoDeps.outputHash or null;
  raw_cargo_lock =
    if pkg ? cargoDeps.lockFile then
      let
        inherit (pkg.cargoDeps) lockFile;
        res = builtins.tryEval (sanitizePosition {
          file = toString lockFile;
        });
      in
      if res.success then res.value.file else false
    else
      null;
  composer_deps = pkg.composerRepository.outputHash or null;
  npm_deps = pkg.npmDeps.outputHash or null;
  yarn_deps = pkg.offlineCache.outputHash or null;
  maven_deps = pkg.fetchedMavenDeps.outputHash or null;
  tests = builtins.attrNames (pkg.passthru.tests or {});
  has_update_script = false;
  src_homepage = pkg.src.meta.homepage or null;
  changelog = pkg.meta.changelog or null;
  maintainers = pkg.meta.maintainers or null;
} --extra-experimental-features flakes nix-command
error:
       … while evaluating attribute 'filename'

         at «string»:27:3:

           26|   inherit raw_version_position;
           27|   filename = position.file;
             |   ^
           28|   line = position.line;

       … from call site

         at «string»:22:5:

           21|    else
           22|     sanitizePosition (builtins.unsafeGetAttrPos "src" pkg);
             |     ^
           23| in {

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: value is null while a set was expected
Traceback (most recent call last):
  File "/nix/store/63zkb5jlwkmgw0xmida3r6pwahbjyx88-nix-update-1.3.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/63zkb5jlwkmgw0xmida3r6pwahbjyx88-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/__init__.py", line 291, in main
    package = update(options)
              ^^^^^^^^^^^^^^^
  File "/nix/store/63zkb5jlwkmgw0xmida3r6pwahbjyx88-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/update.py", line 339, in update
    package = eval_attr(opts)
              ^^^^^^^^^^^^^^^
  File "/nix/store/63zkb5jlwkmgw0xmida3r6pwahbjyx88-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/eval.py", line 205, in eval_attr
    res = run(cmd)
          ^^^^^^^^
  File "/nix/store/63zkb5jlwkmgw0xmida3r6pwahbjyx88-nix-update-1.3.1/lib/python3.11/site-packages/nix_update/utils.py", line 37, in run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--json', '--impure', '--expr', '\nlet\n  \n  inherit (builtins) getFlake stringLength substring;\n  currentSystem = builtins.currentSystem;\n  flake = getFlake "/home/lordmzte/dev/dotfiles";\n  pkg = flake.packages.${currentSystem}."nushell-plugins" or flake."nushell-plugins";\n  inherit (flake) outPath;\n  outPathLen = stringLength outPath;\n  sanitizePosition = { file, ... }@pos:\n        assert substring 0 outPathLen file != outPath\n          -> throw "${file} is not in ${outPath}";\n        pos // { file = "/home/lordmzte/dev/dotfiles" + substring outPathLen (stringLength file - outPathLen) file; };\n\n  raw_version_position = sanitizePosition (builtins.unsafeGetAttrPos "version" pkg);\n\n  position = if pkg ? isRubyGem then\n    raw_version_position\n  else if pkg ? isPhpExtension then\n    raw_version_position\n   else\n    sanitizePosition (builtins.unsafeGetAttrPos "src" pkg);\nin {\n  name = pkg.name;\n  old_version = pkg.version or (builtins.parseDrvName pkg.name).version;\n  inherit raw_version_position;\n  filename = position.file;\n  line = position.line;\n  urls = pkg.src.urls or null;\n  url = pkg.src.url or null;\n  rev = pkg.src.rev or null;\n  hash = pkg.src.outputHash or null;\n  go_modules = pkg.goModules.outputHash or null;\n  go_modules_old = pkg.go-modules.outputHash or null;\n  cargo_deps = pkg.cargoDeps.outputHash or null;\n  raw_cargo_lock =\n    if pkg ? cargoDeps.lockFile then\n      let\n        inherit (pkg.cargoDeps) lockFile;\n        res = builtins.tryEval (sanitizePosition {\n          file = toString lockFile;\n        });\n      in\n      if res.success then res.value.file else false\n    else\n      null;\n  composer_deps = pkg.composerRepository.outputHash or null;\n  npm_deps = pkg.npmDeps.outputHash or null;\n  yarn_deps = pkg.offlineCache.outputHash or null;\n  maven_deps = pkg.fetchedMavenDeps.outputHash or null;\n  tests = builtins.attrNames (pkg.passthru.tests or {});\n  has_update_script = false;\n  src_homepage = pkg.src.meta.homepage or null;\n  changelog = pkg.meta.changelog or null;\n  maintainers = pkg.meta.maintainers or null;\n}', '--extra-experimental-features', 'flakes nix-command']' returned non-zero exit status 1.
```

</details>

System information:
- OS: Arch Linux
- Nix version: nix (Nix) 2.22.1
- nix-update version: 1.3.1

**Comment by Mic92** [comment]
nushell-plugins seems to be a list - nix-update doesn't handle list of packages. Try moving the plugin into a package instead.
You can still add this package to your list.
