### ISSUE TITLE
Lots of releases crowd out relevant version if regex is used

### ISSUE THREAD

**Issue by numinit** [Mic92/nix-update#265]
Hi there @Mic92,

Thanks for the tool, it's been really helpful to reduce maintenance headaches.

I recently noticed this log for Mattermost:

https://nixpkgs-update-logs.nix-community.org/mattermost/2024-07-18.log

The latest version that matches the regex is 9.5.7, but it happens to be on page 3 of the release list.

https://github.com/mattermost/mattermost/releases?page=3

Is there any way we can tune how many GH releases are pulled? Thanks!

**Comment by Mic92** [comment]
It probably should paginate the API until it finds the version.

**Comment by Jaculabilis** [comment]
Specifically for Mattermost, this will be solved by #246, since the API returns 30 responses per page by default instead of the 10 in the Atom feed. If we need more than 30, the GitHub API supports a [`?per_page=`](https://docs.github.com/en/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28#changing-the-number-of-items-per-page) query parameter. I doubt we need to look more than 30 or 50 releases back for any reasonable use case.

So, whenever 1.4.1 or 1.5 is released and makes it into nixpkgs, this should be resolved.

**Comment by numinit** [comment]
Thanks for looking into this @Jaculabilis!

**Comment by Mic92** [comment]
Please re-open if this is not solved by the latest release.

**Comment by numinit** [comment]
Worked great!

https://github.com/NixOS/nixpkgs/pull/335034

**Comment by numinit** [comment]
I am once again seeing this:

```
Going to be running update for following packages:                                                                                                
 - mattermost-10.3.0                                                                                                                              
                                                                                                                                                  
Press Enter key to continue...                                                                                                                    
                                                                                                                                                  
Running update for:                                                                                                                               
 - mattermost-10.3.0: UPDATING ...                                                                                                                
 - mattermost-10.3.0: ERROR                                                                                                                       
                                                                         
--- SHOWING ERROR LOG FOR mattermost-10.3.0 ----------------------                                                                                
                                                                                                                                                  
Traceback (most recent call last):                                                                                                                
  File "/nix/store/5axn4fspdb8lva374h3nz7gm3k9wg56l-nix-update-1.9.0/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/nix/store/5axn4fspdb8lva374h3nz7gm3k9wg56l-nix-update-1.9.0/lib/python3.12/site-packages/nix_update/__init__.py", line 319, in main
    package = update(options)                                                                                                                     
              ^^^^^^^^^^^^^^^
  File "/nix/store/5axn4fspdb8lva374h3nz7gm3k9wg56l-nix-update-1.9.0/lib/python3.12/site-packages/nix_update/update.py", line 508, in update
    update_hash = update_version(                                        
                  ^^^^^^^^^^^^^^^                                                                                                                 
  File "/nix/store/5axn4fspdb8lva374h3nz7gm3k9wg56l-nix-update-1.9.0/lib/python3.12/site-packages/nix_update/update.py", line 439, in update_versi
on                                                                       
    new_version = fetch_latest_version(               
                  ^^^^^^^^^^^^^^^^^^^^^         
  File "/nix/store/5axn4fspdb8lva374h3nz7gm3k9wg56l-nix-update-1.9.0/lib/python3.12/site-packages/nix_update/version/__init__.py", line 128, in fe
tch_latest_version                                                       
    raise VersionError(  
nix_update.errors.VersionError: Not version matched the regex. The following versions were found:
v10.4.1                                                                  
v9.11.7-rc2                                                                                                                                       
v9.11.7-rc1                                                                                                                                       
v10.4.0                      
v10.4.0-rc3                                                              
v10.3.2-rc1                                                              
v10.2.2-rc1                                                              
v10.1.7-rc1                                                                                                                                       
v10.4.0-rc2                                                              
v10.1.6    
```

**Comment by Mic92** [comment]
Github api got reverted in https://github.com/Mic92/nix-update/pull/274 by @lilyinstarlight

**Comment by lilyinstarlight** [comment]
> Github api got reverted in #274 by @lilyinstarlight

GitHub API is fine to use, but do take care not to break update semantics entirely (in a way that can't be worked around) like switching from tags to releases

It seems possible to get tags from the repository REST API (<https://docs.github.com/en/rest/repos/repos#list-repository-tags>) or worst case the general git refs REST API should work as well

**Comment by numinit** [comment]
@lilyinstarlight @Mic92 if we can make use of the GH API opt-in and keep the default behavior? It seems like "project publishes enough releases to crowd out the Atom feed" is an edge case...

**Comment by lilyinstarlight** [comment]
I question the utility of continuing to misuse an atom feed to gather a list of git tags by default if the API is sufficient (I've not attempted to use it, which could find some drawbacks I'm not seeing), and keeping fallback to the atom feed when encountering API problems is likely a good idea

But also I have no stake in the implementation as long as it's not breaking stuff I care about, so y'all can decide however you want to implement a fix
