### ISSUE TITLE
Fail with nix-on-droid

### ISSUE THREAD

**Issue by thesewer** [Mic92/nix-update#286]
```
nix-update drawercli
$ nix eval --json --impure --extra-experimental-features nix-command --expr (
    let
      inputs = (if (builtins.hasAttr "overlays" (builtins.functionArgs (import ./.))) then { overlays = []; } else { });
    in
    with import ./. inputs;
    let
      pkg = drawercli;
      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;

      position = if pkg ? isRubyGem then
        raw_version_position
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      inherit raw_version_position;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash or null;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoHash or pkg.cargoSha256 or null;
      tests = builtins.attrNames (pkg.passthru.tests or {});
    })
error: opening file '/data/data/com.termux.nix/files/home/default.nix': No such file or directory
Traceback (most recent call last):
  File "/nix/store/z8ghpmck7qvxi4a6ykz4s51na4rgyngf-nix-update-0.5.1/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/z8ghpmck7qvxi4a6ykz4s51na4rgyngf-nix-update-0.5.1/lib/python3.9/site-packages/nix_update/__init__.py", line 217, in main
    package = update(options)
  File "/nix/store/z8ghpmck7qvxi4a6ykz4s51na4rgyngf-nix-update-0.5.1/lib/python3.9/site-packages/nix_update/update.py", line 140, in update
    package = eval_attr(opts)
  File "/nix/store/z8ghpmck7qvxi4a6ykz4s51na4rgyngf-nix-update-0.5.1/lib/python3.9/site-packages/nix_update/eval.py", line 89, in eval_attr
    res = run(cmd)
  File "/nix/store/z8ghpmck7qvxi4a6ykz4s51na4rgyngf-nix-update-0.5.1/lib/python3.9/site-packages/nix_update/utils.py", line 35, in run
    return subprocess.run(
  File "/nix/store/7iirzlgw3m77vyclz3hi9g6wmwicqvjh-python3-3.9.16/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--json', '--impure', '--extra-experimental-features', 'nix-command', '--expr', '(\n    let\n      inputs = (if (builtins.hasAttr "overlays" (builtins.functionArgs (import ./.))) then { overlays = []; } else { });\n    in\n    with import ./. inputs;\n    let\n      pkg = drawercli;\n      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;\n\n      position = if pkg ? isRubyGem then\n        raw_version_position\n      else\n        builtins.unsafeGetAttrPos "src" pkg;\n    in {\n      name = pkg.name;\n      old_version = (builtins.parseDrvName pkg.name).version;\n      inherit raw_version_position;\n      filename = position.file;\n      line = position.line;\n      urls = pkg.src.urls or null;\n      url = pkg.src.url or null;\n      rev = pkg.src.url.rev or null;\n      hash = pkg.src.outputHash or null;\n      mod_sha256 = pkg.modSha256 or null;\n      vendor_sha256 = pkg.vendorSha256 or null;\n      cargo_sha256 = pkg.cargoHash or pkg.cargoSha256 or null;\n      tests = builtins.attrNames (pkg.passthru.tests or {});\n    })']' returned non-zero exit status 1.
```

**Comment by SuperSandro2000** [comment]
> error: opening file '/data/data/com.termux.nix/files/home/default.nix': No such file or directory

Please follow the instructions [here](https://github.com/Mic92/nix-update#usage). If you want to update a package in nixpkgs, you need to clone the repo first, cd into it and then run nix-update.
