### ISSUE TITLE
Empties package file when updating to the same version

### ISSUE THREAD

**Issue by l0b0** [Mic92/nix-update#295]
To reproduce:

1. Check out https://github.com/NixOS/nixpkgs/pull/350177
2. `nix-update '--version-regex=^v(\d+(\.\d+)*)$' daggerfall-unity`

Console session:

```
❯ nix-update '--version-regex=^v(\d+(\.\d+)*)$' daggerfall-unity
$ nix eval --json --impure --expr 
let
  
  pkgs = import "/home/victor/nixpkgs";
  args =  builtins.functionArgs pkgs;
  inputs = (if args ? system then { system = builtins.currentSystem; } else {}) //
           (if args ? overlays then { overlays = [ ]; } else {});
  pkg = (pkgs inputs)."daggerfall-unity";
  sanitizePosition = x: x;

  positionFromMeta = pkg: let
    parts = builtins.match "(.*):([0-9]+)" pkg.meta.position;
  in {
    file = builtins.elemAt parts 0;
    line = builtins.fromJSON (builtins.elemAt parts 1);
  };

  raw_version_position = sanitizePosition (builtins.unsafeGetAttrPos "version" pkg);

  position = if pkg ? isRubyGem then
    raw_version_position
  else if pkg ? isPhpExtension then
    raw_version_position
  else if (builtins.unsafeGetAttrPos "src" pkg) != null then
    sanitizePosition (builtins.unsafeGetAttrPos "src" pkg)
  else
    sanitizePosition (positionFromMeta pkg);
in {
  name = pkg.name;
  old_version = pkg.version or (builtins.parseDrvName pkg.name).version;
  inherit raw_version_position;
  filename = position.file;
  line = position.line;
  urls = pkg.src.urls or null;
  url = pkg.src.url or null;
  rev = pkg.src.rev or null;
  hash = pkg.src.outputHash or null;
  go_modules = pkg.goModules.outputHash or null;
  go_modules_old = pkg.go-modules.outputHash or null;
  cargo_deps = pkg.cargoDeps.outputHash or null;
  raw_cargo_lock =
    if pkg ? cargoDeps.lockFile then
      let
        inherit (pkg.cargoDeps) lockFile;
        res = builtins.tryEval (sanitizePosition {
          file = toString lockFile;
        });
      in
      if res.success then res.value.file else false
    else
      null;
  composer_deps = pkg.composerRepository.outputHash or null;
  npm_deps = pkg.npmDeps.outputHash or null;
  pnpm_deps = pkg.pnpmDeps.outputHash or null;
  yarn_deps = pkg.offlineCache.outputHash or null;
  maven_deps = pkg.fetchedMavenDeps.outputHash or null;
  mix_deps = pkg.mixFodDeps.outputHash or null;
  tests = builtins.attrNames (pkg.passthru.tests or {});
  has_update_script = pkg.passthru.updateScript or null != null;
  src_homepage = pkg.src.meta.homepage or null;
  changelog = pkg.meta.changelog or null;
  maintainers = pkg.meta.maintainers or null;
} --extra-experimental-features flakes nix-command
fetch https://github.com/Interkarma/daggerfall-unity/releases.atom
$ git diff --color=never --word-diff=porcelain -- /home/victor/nixpkgs/pkgs/by-name/da/daggerfall-unity/package.nix
Update 1.1.1 -> 1.1.1 in /home/victor/nixpkgs/pkgs/by-name/da/daggerfall-unity/package.nix
Traceback (most recent call last):
  File "/nix/store/zgz97bjlbcjbnik6p69wiyblxpn03jv0-nix-update-1.5.2/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/zgz97bjlbcjbnik6p69wiyblxpn03jv0-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/__init__.py", line 311, in main
    package = update(options)
              ^^^^^^^^^^^^^^^
  File "/nix/store/zgz97bjlbcjbnik6p69wiyblxpn03jv0-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/update.py", line 449, in update
    update_hash = update_version(
                  ^^^^^^^^^^^^^^^
  File "/nix/store/zgz97bjlbcjbnik6p69wiyblxpn03jv0-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/update.py", line 422, in update_version
    return replace_version(package)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zgz97bjlbcjbnik6p69wiyblxpn03jv0-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/update.py", line 41, in replace_version
    line = line.replace(package.rev, package.new_version.rev)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 1 must be str, not None
```

Update: Still present in 1.7.0.

**Comment by Mic92** [comment]
Maybe fixed by https://github.com/Mic92/nix-update/pull/313 ?
Please re-open otherwise.

**Comment by l0b0** [comment]
Confirmed fixed with the following commands:

```
git checkout daggerfall-unity
git rebase 001db3e8cb8e97edaf6b9e494a4ecb6d479e0732 # nix-update: 1.7.0 -> 1.9.0 (#370820) commit
"$(nix-build -A nix-update --no-out-link)/bin/nix-update" '--version-regex=^v(\d+(\.\d+)*)$' daggerfall-unity
```

Thank you!
