### ISSUE TITLE
Unrelated file in project source causing update to fail

### ISSUE THREAD

**Issue by eureka-cpu** [Mic92/nix-update#303]
I have this package that I'm overriding, looks like this:
```nix
{ flatbuffers
, fetchFromGitHub
}:

(flatbuffers.overrideAttrs (old: rec {
  version = "24.3.25";
  src = fetchFromGitHub {
    inherit (old.src) owner repo;
    rev = "v${version}";
    hash = "sha256-uE9CQnhzVgOweYLhWPn2hvzXHyBbFiFVESJ1AEM3BmA=";
  };
}))
```
I'm re-exporting this as a package in my flake as `flatc`. When I run `nix-update flatc --flake --version=24.3.25` this is the output:
```
error (ignored): error: reached end of FramedSource
error:
       … while evaluating attribute 'cargo_deps'

         at «string»:44:3:

           43|   go_modules_old = pkg.go-modules.outputHash or null;
           44|   cargo_deps = pkg.cargoDeps.outputHash or null;
             |   ^
           45|   raw_cargo_lock =

       … while calling the 'getFlake' builtin

         at «string»:6:11:

            5|   currentSystem = builtins.currentSystem;
            6|   flake = getFlake "/home/eureka/Code/Anagram/bonsol";
             |           ^
            7|   pkg = flake.packages.${currentSystem}."flatc" or flake."flatc";

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file '/home/eureka/Code/Anagram/bonsol/test-ledger/admin.rpc' has an unsupported type
Traceback (most recent call last):
  File "/nix/store/sy4nw98mprmxcf8xpqzqm227ghhvaakq-nix-update-1.5.2/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/sy4nw98mprmxcf8xpqzqm227ghhvaakq-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/__init__.py", line 311, in main
    package = update(options)
              ^^^^^^^^^^^^^^^
  File "/nix/store/sy4nw98mprmxcf8xpqzqm227ghhvaakq-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/update.py", line 426, in update
    package = eval_attr(opts)
              ^^^^^^^^^^^^^^^
  File "/nix/store/sy4nw98mprmxcf8xpqzqm227ghhvaakq-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/eval.py", line 218, in eval_attr
    res = run(cmd)
          ^^^^^^^^
  File "/nix/store/sy4nw98mprmxcf8xpqzqm227ghhvaakq-nix-update-1.5.2/lib/python3.12/site-packages/nix_update/utils.py", line 37, in run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--json', '--impure', '--expr', '\nlet\n  \n  inherit (builtins) getFlake stringLength substring;\n  currentSystem = builtins.currentSystem;\n  flake = getFlake "/home/eureka/Code/Anagram/bonsol";\n  pkg = flake.packages.${currentSystem}."flatc" or flake."flatc";\n  inherit (flake) outPath;\n  outPathLen = stringLength outPath;\n  sanitizePosition = { file, ... }@pos:\n        assert substring 0 outPathLen file != outPath\n          -> throw "${file} is not in ${outPath}";\n        pos // { file = "/home/eureka/Code/Anagram/bonsol" + substring outPathLen (stringLength file - outPathLen) file; };\n\n  positionFromMeta = pkg: let\n    parts = builtins.match "(.*):([0-9]+)" pkg.meta.position;\n  in {\n    file = builtins.elemAt parts 0;\n    line = builtins.fromJSON (builtins.elemAt parts 1);\n  };\n\n  raw_version_position = sanitizePosition (builtins.unsafeGetAttrPos "version" pkg);\n\n  position = if pkg ? isRubyGem then\n    raw_version_position\n  else if pkg ? isPhpExtension then\n    raw_version_position\n  else if (builtins.unsafeGetAttrPos "src" pkg) != null then\n    sanitizePosition (builtins.unsafeGetAttrPos "src" pkg)\n  else\n    sanitizePosition (positionFromMeta pkg);\nin {\n  name = pkg.name;\n  old_version = pkg.version or (builtins.parseDrvName pkg.name).version;\n  inherit raw_version_position;\n  filename = position.file;\n  line = position.line;\n  urls = pkg.src.urls or null;\n  url = pkg.src.url or null;\n  rev = pkg.src.rev or null;\n  hash = pkg.src.outputHash or null;\n  go_modules = pkg.goModules.outputHash or null;\n  go_modules_old = pkg.go-modules.outputHash or null;\n  cargo_deps = pkg.cargoDeps.outputHash or null;\n  raw_cargo_lock =\n    if pkg ? cargoDeps.lockFile then\n      let\n        inherit (pkg.cargoDeps) lockFile;\n        res = builtins.tryEval (sanitizePosition {\n          file = toString lockFile;\n        });\n      in\n      if res.success then res.value.file else false\n    else\n      null;\n  composer_deps = pkg.composerRepository.outputHash or null;\n  npm_deps = pkg.npmDeps.outputHash or null;\n  pnpm_deps = pkg.pnpmDeps.outputHash or null;\n  yarn_deps = pkg.offlineCache.outputHash or null;\n  maven_deps = pkg.fetchedMavenDeps.outputHash or null;\n  mix_deps = pkg.mixFodDeps.outputHash or null;\n  tests = builtins.attrNames (pkg.passthru.tests or {});\n  has_update_script = false;\n  src_homepage = pkg.src.meta.homepage or null;\n  changelog = pkg.meta.changelog or null;\n  maintainers = pkg.meta.maintainers or null;\n}', '--extra-experimental-features', 'flakes nix-command']' returned non-zero exit status 1.
```
It seems to be getting hung up on some unrelated file, although this is my first time trying out this tool so I could be wrong. Any tips on how to get past this?

**Comment by Mic92** [comment]
If `nix eval` doesn't work, nix-update cannot do much about it. Best thing to do is having nix not import those files. If you use flakes, you could have those not be added by git.
Otherwise there are helper functions to filter out sources like this: https://github.com/nix-community/nix-unit/blob/6d373fdb344760d9c2e45994420b165b0202556b/default.nix#L18

Those have to be used instead of `./.` or whatever is used in your nix builds to import your package source.

**Comment by eureka-cpu** [comment]
I'll try that, but everything else does seem to work fine as it is
