### ISSUE TITLE
error: syntax error, unexpected ')', expecting ';', at (string):5:346

### ISSUE THREAD

**Issue by bbigras** [Mic92/nix-update#50]
I'm using flakes.

`nix run github:Mic92/nix-update syncthing`

```
$ nix-prefetch { sha256 }: (import ./. (if (builtins.hasAttr "config" (builtins.functionArgs (import ./.))) then { config.checkMeta = false; } else { }))).syncthing.go-modules.overrideAttrs (_: { vendorSha256 = sha256; })
warning: unknown setting 'experimental-features'
warning: unknown setting 'experimental-features'
error: syntax error, unexpected ')', expecting ';', at (string):5:346
Traceback (most recent call last):
  File "/nix/store/amswx23as857lf0ds13av8jgwyadhymd-nix-update/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/amswx23as857lf0ds13av8jgwyadhymd-nix-update/lib/python3.8/site-packages/nix_update/__init__.py", line 194, in main
    package = update(options)
  File "/nix/store/amswx23as857lf0ds13av8jgwyadhymd-nix-update/lib/python3.8/site-packages/nix_update/update.py", line 155, in update
    update_go_vendor_hash(opts, package.filename, package.vendor_sha256)
  File "/nix/store/amswx23as857lf0ds13av8jgwyadhymd-nix-update/lib/python3.8/site-packages/nix_update/update.py", line 102, in update_go_vendor_hash
    target_hash = nix_prefetch([expr])
  File "/nix/store/amswx23as857lf0ds13av8jgwyadhymd-nix-update/lib/python3.8/site-packages/nix_update/update.py", line 77, in nix_prefetch
    res = run(["nix-prefetch"] + cmd, extra_env=extra_env)
  File "/nix/store/amswx23as857lf0ds13av8jgwyadhymd-nix-update/lib/python3.8/site-packages/nix_update/utils.py", line 35, in run
    return subprocess.run(
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '{ sha256 }: (import ./. (if (builtins.hasAttr "config" (builtins.functionArgs (import ./.))) then { config.checkMeta = false; } else { }))).syncthing.go-modules.overrideAttrs (_: { vendorSha256 = sha256; })']' returned non-zero exit status 1.
```

**Comment by SuperSandro2000** [comment]
Can you test https://github.com/Mic92/nix-update/pull/51? Worked for me.

**Comment by bbigras** [comment]
`nix --experimental-features "nix-command flakes" run github:SuperSandro2000/nix-update/patch-1 syncthing`

```
warning: unknown setting 'experimental-features'
warning: unknown setting 'experimental-features'
error: syntax error, unexpected ';', expecting ')', at (string):5:276
Traceback (most recent call last):
  File "/nix/store/rl2dvvgkqh5xdwmlk69j3ywpv8sz58z6-nix-update/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/rl2dvvgkqh5xdwmlk69j3ywpv8sz58z6-nix-update/lib/python3.8/site-packages/nix_update/__init__.py", line 194, in main
    package = update(options)
  File "/nix/store/rl2dvvgkqh5xdwmlk69j3ywpv8sz58z6-nix-update/lib/python3.8/site-packages/nix_update/update.py", line 152, in update
    update_src_hash(opts, package.filename, package.hash)
  File "/nix/store/rl2dvvgkqh5xdwmlk69j3ywpv8sz58z6-nix-update/lib/python3.8/site-packages/nix_update/update.py", line 90, in update_src_hash
    target_hash = nix_prefetch([expr])
  File "/nix/store/rl2dvvgkqh5xdwmlk69j3ywpv8sz58z6-nix-update/lib/python3.8/site-packages/nix_update/update.py", line 77, in nix_prefetch
    res = run(["nix-prefetch"] + cmd, extra_env=extra_env)
  File "/nix/store/rl2dvvgkqh5xdwmlk69j3ywpv8sz58z6-nix-update/lib/python3.8/site-packages/nix_update/utils.py", line 35, in run
    return subprocess.run(
  File "/nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '(import ./. (if (builtins.hasAttr "config" (builtins.functionArgs (import ./.))) then { config.checkMeta = false; } else { }).syncthing']' returned non-zero exit status 1.
```

**Comment by Mic92** [comment]
https://github.com/Mic92/nix-update/pull/52

**Comment by bbigras** [comment]
> #52

It works :)
