### ISSUE TITLE
package doesn't build correctly

### ISSUE THREAD

**Issue by goffrie** [Mic92/nix-update#6]
I tried building nix-update but running it gives this error:

```
% /nix/store/3qf1766s2bkwfryawdlnznzyx9ww56n2-nix-update-2020-04-21/bin/nix-update  
Traceback (most recent call last):
  File "/nix/store/3qf1766s2bkwfryawdlnznzyx9ww56n2-nix-update-2020-04-21/bin/.nix-update-wrapped", line 6, in <module>
    from nix_update import main
  File "/nix/store/3qf1766s2bkwfryawdlnznzyx9ww56n2-nix-update-2020-04-21/lib/python3.7/site-packages/nix_update/__init__.py", line 9, in <module>
    from .update import update
  File "/nix/store/3qf1766s2bkwfryawdlnznzyx9ww56n2-nix-update-2020-04-21/lib/python3.7/site-packages/nix_update/update.py", line 9, in <module>
    from .version import fetch_latest_version
ModuleNotFoundError: No module named 'nix_update.version'
```

It seems that the `version` module is not included by setuptools at build time:

```
Executing setuptoolsBuildPhase
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/nix_update
copying nix_update/utils.py -> build/lib/nix_update
copying nix_update/update.py -> build/lib/nix_update
copying nix_update/options.py -> build/lib/nix_update
copying nix_update/eval.py -> build/lib/nix_update
copying nix_update/errors.py -> build/lib/nix_update
copying nix_update/__init__.py -> build/lib/nix_update
running egg_info
creating nix_update.egg-info
writing nix_update.egg-info/PKG-INFO
writing dependency_links to nix_update.egg-info/dependency_links.txt
writing entry points to nix_update.egg-info/entry_points.txt
writing top-level names to nix_update.egg-info/top_level.txt
writing manifest file 'nix_update.egg-info/SOURCES.txt'
reading manifest file 'nix_update.egg-info/SOURCES.txt'
writing manifest file 'nix_update.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/nix_update
copying build/lib/nix_update/__init__.py -> build/bdist.linux-x86_64/wheel/nix_update
copying build/lib/nix_update/errors.py -> build/bdist.linux-x86_64/wheel/nix_update
copying build/lib/nix_update/eval.py -> build/bdist.linux-x86_64/wheel/nix_update
copying build/lib/nix_update/options.py -> build/bdist.linux-x86_64/wheel/nix_update
copying build/lib/nix_update/update.py -> build/bdist.linux-x86_64/wheel/nix_update
copying build/lib/nix_update/utils.py -> build/bdist.linux-x86_64/wheel/nix_update
running install_egg_info
Copying nix_update.egg-info to build/bdist.linux-x86_64/wheel/nix_update-0.0.0-py3.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/nix_update-0.0.0.dist-info/WHEEL
creating 'dist/nix_update-0.0.0-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'nix_update/__init__.py'
adding 'nix_update/errors.py'
adding 'nix_update/eval.py'
adding 'nix_update/options.py'
adding 'nix_update/update.py'
adding 'nix_update/utils.py'
adding 'nix_update-0.0.0.dist-info/LICENSE.rst'
adding 'nix_update-0.0.0.dist-info/METADATA'
adding 'nix_update-0.0.0.dist-info/WHEEL'
adding 'nix_update-0.0.0.dist-info/entry_points.txt'
adding 'nix_update-0.0.0.dist-info/top_level.txt'
adding 'nix_update-0.0.0.dist-info/zip-safe'
adding 'nix_update-0.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
```

I tried using both NUR and `nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz` from the root of this repo.

**Comment by Mic92** [comment]
Indeed. This is weird.
