### ISSUE TITLE
error: assertion '(stdenv).isLinux' failed

### ISSUE THREAD

**Issue by happysalada** [Mic92/nix-update#62]
trying to run the command `nix-update caddy` I'm getting the following error

```
❯ nix-update caddy
$ nix eval --json --impure --experimental-features nix-command --expr (with import ./. {};
    let
      pkg = caddy;
      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;

      position = if pkg ? isRubyGem then
        raw_version_position
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      inherit raw_version_position;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoSha256 or null;
      tests = pkg.passthru.tests or null;
    })
error: assertion '(stdenv).isLinux' failed

       at /Users/raphael/Projects/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:69:1:

           68|
           69| assert stdenv.isLinux;
             | ^
           70|
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/v719fxgpkqmg5scysxiqmprn52j8sbzj-nix-update-0.4.0/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/v719fxgpkqmg5scysxiqmprn52j8sbzj-nix-update-0.4.0/lib/python3.9/site-packages/nix_update/__init__.py", line 194, in main
    package = update(options)
  File "/nix/store/v719fxgpkqmg5scysxiqmprn52j8sbzj-nix-update-0.4.0/lib/python3.9/site-packages/nix_update/update.py", line 140, in update
    package = eval_attr(opts)
  File "/nix/store/v719fxgpkqmg5scysxiqmprn52j8sbzj-nix-update-0.4.0/lib/python3.9/site-packages/nix_update/eval.py", line 84, in eval_attr
    res = run(cmd)
  File "/nix/store/v719fxgpkqmg5scysxiqmprn52j8sbzj-nix-update-0.4.0/lib/python3.9/site-packages/nix_update/utils.py", line 35, in run
    return subprocess.run(
  File "/nix/store/ad19ya4siaxhz63w0m8xh97067iahks0-python3-3.9.6/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--json', '--impure', '--experimental-features', 'nix-command', '--expr', '(with import ./. {};\n    let\n      pkg = caddy;\n      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;\n\n      position = if pkg ? isRubyGem then\n        raw_version_position\n      else\n        builtins.unsafeGetAttrPos "src" pkg;\n    in {\n      name = pkg.name;\n      old_version = (builtins.parseDrvName pkg.name).version;\n      inherit raw_version_position;\n      filename = position.file;\n      line = position.line;\n      urls = pkg.src.urls or null;\n      url = pkg.src.url or null;\n      rev = pkg.src.url.rev or null;\n      hash = pkg.src.outputHash;\n      mod_sha256 = pkg.modSha256 or null;\n      vendor_sha256 = pkg.vendorSha256 or null;\n      cargo_sha256 = pkg.cargoSha256 or null;\n      tests = pkg.passthru.tests or null;\n    })']' returned non-zero exit status 1
```

even though caddy builds fine on darwin.
Let me know if I you need more details.

**Comment by SuperSandro2000** [comment]
Can you execute the following and paste the trace?
```ShellSession
$ nix eval --json --impure --experimental-features nix-command --expr --show-trace '(with import ./. {};
    let
      pkg = caddy;
      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;

      position = if pkg ? isRubyGem then
        raw_version_position
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      inherit raw_version_position;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoSha256 or null;
      tests = pkg.passthru.tests or null;
    })'
```

**Comment by happysalada** [comment]
--show-trace should come before --expr

```
error: assertion '(stdenv).isLinux' failed

       at /Users/raphael/Projects/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:69:1:

           68|
           69| assert stdenv.isLinux;
             | ^
           70|

       … while evaluating anonymous lambda

       at /Users/raphael/Projects/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:1:1:

            1| { buildPackages
             | ^
            2| , callPackage

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|

       … while evaluating 'makeOverridable'

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:67:24:

           66|   */
           67|   makeOverridable = f: origArgs:
             |                        ^
           68|     let

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:121:8:

          120|       auto = builtins.intersectAttrs (lib.functionArgs f) autoArgs;
          121|     in makeOverridable f (auto // args);
             |        ^
          122|

       … while evaluating 'callPackageWith'

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:117:35:

          116|   */
          117|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          118|     let

       … from call site

       at /Users/raphael/Projects/nixpkgs/pkgs/top-level/all-packages.nix:21608:23:

        21607|
        21608|   buildLinux = attrs: callPackage ../os-specific/linux/kernel/generic.nix attrs;
             |                       ^
        21609|

       … while evaluating 'buildLinux'

       at /Users/raphael/Projects/nixpkgs/pkgs/top-level/all-packages.nix:21608:16:

        21607|
        21608|   buildLinux = attrs: callPackage ../os-specific/linux/kernel/generic.nix attrs;
             |                ^
        21609|

       … from call site

       at /Users/raphael/Projects/nixpkgs/pkgs/os-specific/linux/kernel/linux-5.10.nix:5:1:

            4|
            5| buildLinux (args // rec {
             | ^
            6|   version = "5.10.57";

       … while evaluating anonymous lambda

       at /Users/raphael/Projects/nixpkgs/pkgs/os-specific/linux/kernel/linux-5.10.nix:1:1:

            1| { lib, buildPackages, fetchurl, perl, buildLinux, nixosTests, modDirVersionArg ? null, ... } @ args:
             | ^
            2|

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|

       … while evaluating 'makeOverridable'

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:67:24:

           66|   */
           67|   makeOverridable = f: origArgs:
             |                        ^
           68|     let

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:121:8:

          120|       auto = builtins.intersectAttrs (lib.functionArgs f) autoArgs;
          121|     in makeOverridable f (auto // args);
             |        ^
          122|

       … while evaluating 'callPackageWith'

       at /Users/raphael/Projects/nixpkgs/lib/customisation.nix:117:35:

          116|   */
          117|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          118|     let

       … from call site

       at /Users/raphael/Projects/nixpkgs/pkgs/top-level/all-packages.nix:21169:16:

        21168|
        21169|   linux_5_10 = callPackage ../os-specific/linux/kernel/linux-5.10.nix {
             |                ^
        21170|     kernelPatches = [

       … while evaluating the attribute 'linux_5_10'

       at /Users/raphael/Projects/nixpkgs/pkgs/top-level/all-packages.nix:21169:3:

        21168|
        21169|   linux_5_10 = callPackage ../os-specific/linux/kernel/linux-5.10.nix {
             |   ^
        21170|     kernelPatches = [

       … while evaluating the attribute 'kernel.override'

       at /Users/raphael/Projects/nixpkgs/pkgs/top-level/all-packages.nix:21256:5:

        21255|
        21256|     kernel = kernel_;
             |     ^
        21257|     inherit (kernel) stdenv; # in particular, use the same compiler by default

       … while evaluating the attribute 'boot.kernelPackages.kernel'

       at /Users/raphael/Projects/nixpkgs/nixos/modules/system/boot/kernel.nix:41:9:

           40|       apply = kernelPackages: kernelPackages.extend (self: super: {
           41|         kernel = super.kernel.override (originalArgs: {
             |         ^
           42|           inherit randstructSeed;

       … while evaluating the attribute 'content'

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:693:14:

          692|     { _type = "if";
          693|       inherit condition content;
             |              ^
          694|     };

       … while evaluating 'dischargeProperties'

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:609:25:

          608|   */
          609|   dischargeProperties = def:
             |                         ^
          610|     if def._type or "" == "merge" then

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:615:11:

          614|         if def.condition then
          615|           dischargeProperties def.content
             |           ^
          616|         else

       … while evaluating 'dischargeProperties'

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:609:25:

          608|   */
          609|   dischargeProperties = def:
             |                         ^
          610|     if def._type or "" == "merge" then

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:538:137:

          537|         defs' = concatMap (m:
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          539|         ) defs;

       … while evaluating definitions from `/Users/raphael/Projects/nixpkgs/nixos/modules/system/boot/kernel.nix':

       … while evaluating anonymous lambda

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:537:28:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                            ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:537:17:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                 ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:650:7:

          649|     in {
          650|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          651|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:551:9:

          550|       in {
          551|         values = defs''';
             |         ^
          552|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:557:5:

          556|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          557|     mergedValue =
             |     ^
          558|       if isDefined then

       … while evaluating the option `assertions':

       … while evaluating the attribute 'value'

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:525:9:

          524|     in warnDeprecation opt //
          525|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          526|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /Users/raphael/Projects/nixpkgs/lib/modules.nix:140:72:

          139|           # For definitions that have an associated option
          140|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          141|

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/attrsets.nix:301:20:

          300|               then recurse (path ++ [name]) value
          301|               else f (path ++ [name]) value;
             |                    ^
          302|         in mapAttrs g set;

       … while evaluating 'g'

       at /Users/raphael/Projects/nixpkgs/lib/attrsets.nix:298:19:

          297|           g =
          298|             name: value:
             |                   ^
          299|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'assertions'

       … while evaluating 'fold''

       at /Users/raphael/Projects/nixpkgs/lib/lists.nix:55:15:

           54|       len = length list;
           55|       fold' = n:
             |               ^
           56|         if n == len

       … from call site

       at /Users/raphael/Projects/nixpkgs/lib/lists.nix:59:8:

           58|         else op (elemAt list n) (fold' (n + 1));
           59|     in fold' 0;
             |        ^
           60|

       … while evaluating 'foldr'

       at /Users/raphael/Projects/nixpkgs/lib/lists.nix:52:20:

           51|   */
           52|   foldr = op: nul: list:
             |                    ^
           53|     let

       … from call site

       at /Users/raphael/Projects/nixpkgs/nixos/modules/system/activation/top-level.nix:128:12:

          127|   # Replace runtime dependencies
          128|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
          129|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while evaluating the attribute 'system.build.toplevel'

       at /Users/raphael/Projects/nixpkgs/nixos/modules/system/activation/top-level.nix:293:5:

          292|
          293|     system.build.toplevel = system;
             |     ^
          294|

       … while evaluating the attribute 'buildCommand' of the derivation 'nixos-vm'

       at /Users/raphael/Projects/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while evaluating the attribute 'buildCommand' of the derivation 'nixos-test-driver-caddy'

       at /Users/raphael/Projects/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while evaluating the attribute 'buildCommand' of the derivation 'vm-test-run-caddy'

       at /Users/raphael/Projects/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let
{"cargo_sha256":null,"filename":"/Users/raphael/Projects/nixpkgs/pkgs/servers/caddy/default.nix","hash":"sha256-Wc7eNw5FZWoUT6IP84NhROC59bf4/RCw/gOWLuYI2dc=","line":9,"mod_sha256":null,"name":"caddy-2.4.1","old_version":"2.4.1","raw_version_position":{"column":3,"file":"/Users/raphael/Projects/nixpkgs/pkgs/servers/caddy/default.nix","line":5},"rev":null,"tests":{"caddy":}}
```

**Comment by Mic92** [comment]
Ah. it's because we do `tests = pkg.passthru.tests or null;` which tries to load vm tests...

**Comment by Mic92** [comment]
can you check if https://github.com/Mic92/nix-update/pull/63 fixes your issue?
