### ISSUE TITLE
Do not rely on NIX_PATH

### ISSUE THREAD

**Issue by jtojnar** [Mic92/nix-update#75]
I do not have `NIX_PATH` set to avoid impurities but `nix-update` does not seem to work without it:

```python-traceback
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
Traceback (most recent call last):
  File "/nix/store/nhgmx5zj3z7cdd9z6ipqwv6ammigq96l-nix-update-0.5.0/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/nhgmx5zj3z7cdd9z6ipqwv6ammigq96l-nix-update-0.5.0/lib/python3.9/site-packages/nix_update/__init__.py", line 196, in main
    package = update(options)
  File "/nix/store/nhgmx5zj3z7cdd9z6ipqwv6ammigq96l-nix-update-0.5.0/lib/python3.9/site-packages/nix_update/update.py", line 150, in update
    update_src_hash(opts, package.filename, package.hash)
  File "/nix/store/nhgmx5zj3z7cdd9z6ipqwv6ammigq96l-nix-update-0.5.0/lib/python3.9/site-packages/nix_update/update.py", line 90, in update_src_hash
    target_hash = nix_prefetch([expr])
  File "/nix/store/nhgmx5zj3z7cdd9z6ipqwv6ammigq96l-nix-update-0.5.0/lib/python3.9/site-packages/nix_update/update.py", line 77, in nix_prefetch
    res = run(["nix-prefetch"] + cmd, extra_env=extra_env)
  File "/nix/store/nhgmx5zj3z7cdd9z6ipqwv6ammigq96l-nix-update-0.5.0/lib/python3.9/site-packages/nix_update/utils.py", line 35, in run
    return subprocess.run(
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '(import ./. (if (builtins.hasAttr "config" (builtins.functionArgs (import ./.))) then { config.checkMeta = false; overlays = []; } else { })).rescrobbled']' returned non-zero exit status 1.
```

This is especially annoying with update scripts that depend on `nix-update`.

It would be nice if the tool did not depend on `<nixpkgs>` or at least fell back on `channel:nixos-unstable` so that I do not have to run it with  `env NIX_PATH=nixpkgs=channel:nixos-unstable`.

**Comment by Mic92** [comment]
I think this is better fixed in `nix-prefetch` directly.

**Comment by jtojnar** [comment]
Right, there are at least two distinct uses of `<nixpkgs>`:

- used as package collection update root – that could be replaced by either `$PWD` or `git rev-parse --show-toplevel`
- used as source for `<nixpkgs/lib>` – possibly copy the required functions in the repo?

**Comment by zowoq** [comment]
`nix-prefetch` was removed in https://github.com/Mic92/nix-update/commit/5692ffc91d61090679f74e5b6f01c87b97b816eb and https://github.com/Mic92/nix-update/commit/fd3202917b9cfc9f077b9619ebd9af1ec09fc4c9 so I think this is resolved?

**Comment by Mic92** [comment]
yep.
