### ISSUE TITLE
`fetchgit` and `hash` don't go together

### ISSUE THREAD

**Issue by dotlambda** [Mic92/nix-update#80]
For expressions that use `fetchgit`, e.g. through `fetchSubmodules = true`, and `hash` instead of `sha256`, nix-update fails to work.
This can e.g. be reproduced with `nix-update --commit chatty --version 0.6.1`:
```
$ git -C ./. diff --staged
$ nix eval --json --impure --experimental-features nix-command --expr (
    let
      inputs = (if (builtins.hasAttr "overlays" (builtins.functionArgs (import ./.))) then { overlays = []; } else { });
    in
    with import ./. inputs;
    let
      pkg = chatty;
      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;

      position = if pkg ? isRubyGem then
        raw_version_position
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      inherit raw_version_position;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash or null;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoHash or pkg.cargoSha256 or null;
      tests = builtins.attrNames (pkg.passthru.tests or {});
    })
Update 0.6.0 -> 0.6.1 in ./pkgs/applications/networking/instant-messengers/chatty/default.nix
$ nix-prefetch (import ./. (if (builtins.hasAttr "config" (builtins.functionArgs (import ./.))) then { config.checkMeta = false; overlays = []; } else { })).chatty
error: Only one of sha256 or hash can be set
```
I also don't understand why `nix-update --commit chatty` fails to find the newest version but assume it's because internally `fetchgit` is used.

**Comment by azahi** [comment]
I'm hitting the same problem but with `fetcFromhGitHub`/`hash` and `vendorHash` for `buildGoModule` packages, setting `fetcFromhGitHub`/`sha256` and `vendorSha256` works fine.

<details>
<summary>Log</summary>

```
[azahi@melian:~/src/nixpkgs]$ nix run nixpkgs#nix-update -- exportarr
$ nix eval --json --impure --extra-experimental-features nix-command --expr (
    let
      inputs = (if (builtins.hasAttr "overlays" (builtins.functionArgs (import ./.))) then { overlays = []; } else { });
    in
    with import ./. inputs;
    let
      pkg = exportarr;
      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;

      position = if pkg ? isRubyGem then
        raw_version_position
      else
        builtins.unsafeGetAttrPos "src" pkg;
    in {
      name = pkg.name;
      old_version = (builtins.parseDrvName pkg.name).version;
      inherit raw_version_position;
      filename = position.file;
      line = position.line;
      urls = pkg.src.urls or null;
      url = pkg.src.url or null;
      rev = pkg.src.url.rev or null;
      hash = pkg.src.outputHash or null;
      mod_sha256 = pkg.modSha256 or null;
      vendor_sha256 = pkg.vendorSha256 or null;
      cargo_sha256 = pkg.cargoHash or pkg.cargoSha256 or null;
      tests = builtins.attrNames (pkg.passthru.tests or {});
    })
fetch https://github.com/onedr0p/exportarr/releases.atom
Update 1.0.0 -> 1.1.0 in /home/azahi/src/nixpkgs/pkgs/servers/monitoring/prometheus/exportarr/default.nix
$ nix-prefetch (import ./. (if (builtins.hasAttr "config" (builtins.functionArgs (import ./.))) then { config.checkMeta = false; overlays = []; } else { })).exportarr
error: multiple hashes passed to fetchurl
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/yhg3m8ckq0dlgggzh9xv5m8mqxy0drm0-nix-update-0.6.0/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/yhg3m8ckq0dlgggzh9xv5m8mqxy0drm0-nix-update-0.6.0/lib/python3.10/site-packages/nix_update/__init__.py", line 224, in main
    package = update(options)
  File "/nix/store/yhg3m8ckq0dlgggzh9xv5m8mqxy0drm0-nix-update-0.6.0/lib/python3.10/site-packages/nix_update/update.py", line 149, in update
    update_src_hash(opts, package.filename, package.hash)
  File "/nix/store/yhg3m8ckq0dlgggzh9xv5m8mqxy0drm0-nix-update-0.6.0/lib/python3.10/site-packages/nix_update/update.py", line 90, in update_src_hash
    target_hash = nix_prefetch([expr])
  File "/nix/store/yhg3m8ckq0dlgggzh9xv5m8mqxy0drm0-nix-update-0.6.0/lib/python3.10/site-packages/nix_update/update.py", line 77, in nix_prefetch
    res = run(["nix-prefetch"] + cmd, extra_env=extra_env)
  File "/nix/store/yhg3m8ckq0dlgggzh9xv5m8mqxy0drm0-nix-update-0.6.0/lib/python3.10/site-packages/nix_update/utils.py", line 35, in run
    return subprocess.run(
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch', '(import ./. (if (builtins.hasAttr "config" (builtins.functionArgs (import ./.))) then { config.checkMeta = false; overlays = []; } else { })).exportarr']' returned non-zero exit status 1.
```

</details>

**Comment by Mic92** [comment]
I think this needs to be fixed in `nix-prefetch`. In `nix-update` we cannot really control this.

**Comment by winterqt** [comment]
Can y'all test https://github.com/NixOS/nixpkgs/pull/190735, please? Fixes the issue for me, but would appreciate more testing before merging. Thanks!

**Comment by zowoq** [comment]
`hash` has been fixed by applying a patch to `nix-prefetch` in `nixpkgs`.
___
> I'm hitting the same problem but with `fetcFromhGitHub`/`hash` and `vendorHash` for `buildGoModule` packages, setting `fetcFromhGitHub`/`sha256` and `vendorSha256` works fine.

`vendorHash` was added to `nix-update` in https://github.com/Mic92/nix-update/commit/e4de7e6287707d94740d662d7e795e84052b4a00, bumped in nixpkgs in https://github.com/NixOS/nixpkgs/pull/192570
