### ISSUE TITLE
error: value is null while a set was expected

### ISSUE THREAD

**Issue by bbigras** [Mic92/nix-update#89]
`nix run github:Mic92/nix-update anytype`

```
error: value is null while a set was expected

       at «string»:18:18:

           17|       inherit raw_version_position;
           18|       filename = position.file;
             |                  ^
           19|       line = position.line;
Traceback (most recent call last):
  File "/nix/store/i5f1rbgm28nbfawv1byszzmdsh431hq5-nix-update/bin/.nix-update-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/i5f1rbgm28nbfawv1byszzmdsh431hq5-nix-update/lib/python3.9/site-packages/nix_update/__init__.py", line 217, in main
    package = update(options)
  File "/nix/store/i5f1rbgm28nbfawv1byszzmdsh431hq5-nix-update/lib/python3.9/site-packages/nix_update/update.py", line 140, in update
    package = eval_attr(opts)
  File "/nix/store/i5f1rbgm28nbfawv1byszzmdsh431hq5-nix-update/lib/python3.9/site-packages/nix_update/eval.py", line 89, in eval_attr
    res = run(cmd)
  File "/nix/store/i5f1rbgm28nbfawv1byszzmdsh431hq5-nix-update/lib/python3.9/site-packages/nix_update/utils.py", line 35, in run
    return subprocess.run(
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'eval', '--json', '--impure', '--experimental-features', 'nix-command', '--expr', '(\n    let\n      inputs = (if (builtins.hasAttr "overlays" (builtins.functionArgs (import ./.))) then { overlays = []; } else { });\n    in\n    with import ./. inputs;\n    let\n      pkg = anytype;\n      raw_version_position = builtins.unsafeGetAttrPos "version" pkg;\n\n      position = if pkg ? isRubyGem then\n        raw_version_position\n      else\n        builtins.unsafeGetAttrPos "src" pkg;\n    in {\n      name = pkg.name;\n      old_version = (builtins.parseDrvName pkg.name).version;\n      inherit raw_version_position;\n      filename = position.file;\n      line = position.line;\n      urls = pkg.src.urls or null;\n      url = pkg.src.url or null;\n      rev = pkg.src.url.rev or null;\n      hash = pkg.src.outputHash or null;\n      mod_sha256 = pkg.modSha256 or null;\n      vendor_sha256 = pkg.vendorSha256 or null;\n      cargo_sha256 = pkg.cargoHash or pkg.cargoSha256 or null;\n      tests = builtins.attrNames (pkg.passthru.tests or {});\n    })']' returned non-zero exit status 1.
```

**Comment by bbigras** [comment]
Oh wait, anytype is using `fetchurl`. It can't detect the new version.

Sorry.
